### ISSUE TITLE
make the sample go stop

### ISSUE THREAD

**Issue by mrVanDalo** [occulkot/com.occulkot.Freesound.xrnx#1]
- replacing the play button with a stop button, when playing
- replacing the stop button with a play button, when finished playing
- starting another sample will stop the first sample which was played.

(You can give me this ticket, I'll create a pull-request for it).

**Comment by occulkot** [comment]
Sorry for delay, create pull request.

**Comment by mrVanDalo** [comment]
@occulkot can you assign it to me, so it pops up in my todo list, will not do it in the next days, (other plugins need to be finished and updated)

**Comment by mrVanDalo** [comment]
Sorry Forgot about this totally, and now I will not do it anymore. sorry, I will close this ticket.
